"""Build data/enemy-presets.js: the current Anomaly Arbitration bosses as sample enemies.

Reads the Honkai: Star Rail Fandom wiki: the latest Anomaly Arbitration stage page (Knights I-III
and the King in Check), then each boss's infobox (Toughness, Weaknesses) and stats (base SPD,
per-Type RES). Run it after a new Anomaly Arbitration cycle starts; the GitHub workflow in
.github/workflows/enemies.yml runs it weekly.

Enemy SPD at Lv. 86+ is base SPD x 1.32. Weak Types have 0% RES; the wiki lists the rest.
"""
import json
import os
import re
import sys
import urllib.parse
import urllib.request

API = "https://honkai-star-rail.fandom.com/api.php"
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "enemy-presets.js")
TYPES = ["Physical", "Fire", "Ice", "Lightning", "Wind", "Quantum", "Imaginary"]
DATA_TYPE = {"Lightning": "Thunder"}  # the site's data calls Lightning "Thunder"


def wikitext(page):
    url = f"{API}?action=parse&page={urllib.parse.quote(page)}&prop=wikitext&format=json"
    req = urllib.request.Request(url, headers={"User-Agent": "hsr-tools enemy presets"})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    if "parse" not in data:
        raise RuntimeError(f"wiki page not found: {page}")
    return data["parse"]["wikitext"]["*"]


def field(text, name):
    m = re.search(rf"^\|\s*{re.escape(name)}\s*=\s*(.*)$", text, re.M)
    return m.group(1).strip() if m else ""


def spd_mult(level):
    return 1.32 if level >= 86 else 1.2 if level >= 78 else 1.1 if level >= 65 else 1.0


def enemy(name, level):
    t = wikitext(name)
    weak = [w.strip() for w in field(t, "weakness").split(";") if w.strip()]
    stats = t[t.find("{{Enemy Stats"):]
    res = {}
    for ty in TYPES:
        v = field(stats, f"{ty.lower()}_res")
        res[DATA_TYPE.get(ty, ty)] = 0.0 if ty in weak else (float(v) if v else 0.2)
    base_spd = float(field(stats, "spd") or 100)
    # Boss fights with several shared-HP parts ("Enemy List" on the page) have that many targets.
    parts = re.search(r"\{\{Enemy List\|([^}|]+)", t)
    count = len([p for p in parts.group(1).split(";") if p.strip()]) if parts and "Shared HP" in t else 1
    return {
        "name": name,
        "weak": [DATA_TYPE.get(w, w) for w in weak],
        "res": res,
        "baseSpd": base_spd,
        "spd": round(base_spd * spd_mult(level), 1),
        "toughness": int(float(field(t, "tough") or 160)),
        "count": count,
    }


def main():
    hub = wikitext("Anomaly Arbitration/Stages")
    m = re.search(r"\{\{Transclude\|(Anomaly Arbitration/Stages/[\d.]+)\|([^}]+)\}\}", hub)
    if not m:
        sys.exit("Could not find the current Anomaly Arbitration cycle")
    page, cycle = m.group(1), m.group(2).strip()
    version = page.rsplit("/", 1)[1]
    t = wikitext(page)
    knights_block = t[t.find("{{Anomaly Arbitration Knight"):t.find("{{Anomaly Arbitration King")]
    king_block = t[t.find("{{Anomaly Arbitration King"):]
    presets = []
    for i in (1, 2, 3):
        boss = field(knights_block, f"{i}_w2").split(";")[0]
        level = int(field(knights_block, f"{i}_levels") or 95)
        e = enemy(boss, level)
        presets.append({"id": f"knight{i}", "label": f"{version} Knight {'I' * i}: {boss}", "level": level,
                        "cycles": int(field(knights_block, f"{i}_cycles") or 6), **e})
    boss = field(king_block, "w2").split(";")[0]
    level = int(field(king_block, "levels") or 100)
    e = enemy(boss, level)
    presets.insert(0, {"id": "king", "label": f"{version} King in Check: {boss}", "level": level,
                       "cycles": int(field(king_block, "cycles") or 6), **e})
    out = {"version": version, "cycle": cycle, "presets": presets}
    with open(OUT, "w") as f:
        f.write("// Generated by scripts/build_enemies.py from the HSR Fandom wiki. Do not edit by hand.\n")
        f.write(f"window.HSR_ENEMY_PRESETS = {json.dumps(out, indent=1, ensure_ascii=False)};\n")
    print(f"{version} {cycle}: " + "; ".join(f"{p['label']} (SPD {p['spd']}, Toughness {p['toughness']})" for p in presets))


if __name__ == "__main__":
    main()
